package com.bishack.api.service;

public interface IServiceConstants {
	
	String RATING_LEVEL_LOW = "LOW";
	String RATING_LEVEL_MEDIUM = "MEDIUM";
	String RATING_LEVEL_HIGH = "HIGH";
	
	String CAT_SWIFT_VALIDATION = "SWIFT_VALIDATION";
	String CAT_SWIFT_COMPLIANCE = "SWIFT_COMPLIANCE";
	String CAT_INTERNAL_TRX_HIST = "INTERNAL_TRX_HIST";
	String CAT_INTERNAL_COMPLIANCE = "INTERNAL_COMPLIANCE";
	
	String ATTR_AC_FORMAT_VALIDATION = "AC_FORMAT_VALIDATION";
	String ATTR_AC_VERIFICATION = "AC_VERIFICATION";
	String ATTR_TRX_AMOUNT = "TRX_AMOUNT";
	String ATTR_BENFICIARY_INST_RISK = "BENFICIARY_INST_RISK";
	String ATTR_SRC_INST_RISK = "SRC_INST_RISK";
	
	String ATTR_SRC_AVG_TRX_AMOUNT = "SRC_AVG_TRX_AMOUNT";
	String ATTR_SRC_TOTAL_TRX_AMOUNT = "SRC_TOTAL_TRX_AMOUNT";	
	String ATTR_HIGH_RISK_BENE_CNTRY = "HIGH_RISK_BENE_CNTRY";

}
