

DROP TABLE IF EXISTS CUSTOMER_TRX;

    CREATE TABLE CUSTOMER_TRX (
      CUSTOMER_TRX_KEY NUMBER GENERATED ALWAYS AS IDENTITY,
      NAME  VARCHAR2(100) NOT NULL,
      AUTHOR  VARCHAR2(100) NOT NULL,
      DESCRIPTION VARCHAR2(100) NOT NULL,
	  USER_ID NUMBER,
	  CREATED_DT DATE , 
	  CREATED_BY VARCHAR2(100)
  );
  
